format_version: v1.0
configName: mcp9808
folderName: driver-mcp9808
frameworkPath: C:\git\Harmony3
processor: ATSAME54P20A
projectName: driver-mcp9808
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.7.122\atdf\ATSAME54P20A.atdf
